# definicion del replicaset
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: puchito-set
  labels:
    app: puchito-label
spec:
  replicas: 3
  selector:
    matchLabels:
      app: puchito-label   # adopta todos los que tengan este label
# fin del replicaset
# definicion de los pods
  template:
    metadata:
      name: test-python
      labels:
        app: puchito-label
    spec:
      containers:
      - name: python1
        image: python:3.6-alpine
        command: [ 'sh', '-c', 'echo "<h1>estoy con el contenedor python1</h1>" > index.html && python -m http.server 8082' ]
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
      - name: contenedor1
        image: nginx:stable-alpine
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
      hostNetwork: true
      dnsPolicy: Default