apiVersion: v1
kind: Pod
metadata:
  name: puchito
spec:
  containers:
    - name: contenedor1
      image: nginx:stable-alpine
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      ports:
        - containerPort: 80
    # - name: contenedor2
    #   image: nginx:stable-alpine
    #   resources:
    #     limits:
    #       memory: "128Mi"
    #       cpu: "500m"
    #   ports:
    #     - containerPort: 82
    - name: python
      image: python:3.6-alpine
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      command: [ 'sh', '-c', 'echo "<h1>Puchito capo!!!</h1>" > index.html && python -m http.server 8082' ]
      ports:
        - containerPort: 8082
  hostNetwork: true
  dnsPolicy: Default
# ---
# apiVersion: v1
# kind: Pod
# metadata:
#   name: prueba4
# spec:
#   containers:
#     - name: python
#       image: python:3.6-alpine
#       resources:
#         limits:
#           memory: "128Mi"
#           cpu: "500m"
#       command: [ 'sh', '-c', 'echo "<h1>estoy con el contenedor python1</h1>" > index.html && python -m http.server 8082' ]
#       ports:
#         - containerPort: 8082
#     - name: python2
#       image: python:3.6-alpine
#       resources:
#         limits:
#           memory: "128Mi"
#           cpu: "500m"
#       command: [ 'sh', '-c', 'echo "<h1>estoy con el contenedor python2</h1>" > index.html && python -m http.server 8083' ]
#       ports:
#         - containerPort: 8083
#     - name: python3
#       image: python:3.6-alpine
#       resources:
#         limits:
#           memory: "128Mi"
#           cpu: "500m"
#       command: [ 'sh', '-c', 'echo "<h1>estoy con el contenedor python3</h1>" > index.html && python -m http.server 8084' ]
#       ports:
#         - containerPort: 8084
#   hostNetwork: true
#   dnsPolicy: Default