- name: aws EC2 playbook
  hosts: localhost
  vars_files: 
    - "aws_vars.yml"

  tasks:
    - name: ac_fer
      block:

      - name: vpc
        ec2_vpc_net:
          name: "{{ vpc_name }}"
          cidr_block: "{{ vpc_cidr }}"
          region: "{{ region }}"
          state: present
          aws_access_key: "{{ aws_access_key }}"
          aws_secret_key: "{{ aws_secret_key }}"
        register: vpc

      - name: subnet_public
        ec2_vpc_subnet:
          state: present
          vpc_id:  "{{vpc.vpc.id}}" #creeria q lo saca de la vpc que se crea arriba 
          region: "{{ region }}"
          cidr: "{{ subnet_cidr }}"
          aws_access_key: "{{ aws_access_key }}"
          aws_secret_key: "{{ aws_secret_key }}"
          map_public: yes # para que sea publica
          resource_tags:
            Name: "{{ subnet_name }}"
        register: subnet

      - name: security_group
        ec2_group:
          name: ans_sg_fer
          description: DMZ Security Group
          vpc_id: "{{vpc.vpc.id}}" 
          region: "{{ region }}"
          aws_access_key: "{{ aws_access_key }}"
          aws_secret_key: "{{ aws_secret_key }}"
          rules:
            - proto: tcp
              ports:
              - 80
              cidr_ip: 0.0.0.0/0
            - proto: tcp
              ports:
              - 22
              cidr_ip: 0.0.0.0/0
            # ver si tengo que agragr lo de ssh, creeria q no porque con la segunda regla basta 
        register: security_group

      - name: create IGW
        ec2_vpc_igw:
          vpc_id: "{{ vpc['vpc']['id']}}"
          aws_access_key: "{{ aws_access_key }}"
          aws_secret_key: "{{ aws_secret_key }}"
          state: "present"
          tags:
            Name: "ac_ig_fer"
        register: igw

      - name: Route IGW
        ec2_vpc_route_table:
          vpc_id: "{{ vpc['vpc']['id']}}"
          aws_access_key: "{{ aws_access_key }}"
          aws_secret_key: "{{ aws_secret_key }}"
          subnets:
            - "{{ subnet['subnet']['id'] }}"
          routes:
            - dest: 0.0.0.0/0
              gateway_id: "{{ igw['gateway_id'] }}"
          state: "present"
          tags:
            Name: "ac_rt_fer"

      - name: ec2
        ec2: #esta deprecated podria cambiar por ec2_instance
          image: ami-0022f774911c1d690
          wait: yes
          instance_type: t2.micro
          region: "{{ region }}"
          group_id: "{{ security_group.group_id }}"
          vpc_subnet_id: "{{ subnet.subnet.id }}"
          key_name: ac_xl_pract_ssh
          count_tag:
            Name: ans_ec2_fer
          exact_count: 1
          aws_access_key: "{{ aws_access_key }}"
          aws_secret_key: "{{ aws_secret_key }}"
          