#-----------------------deployApp----------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-go-depl
  namespace: prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-go-depl
      tier: backend
  template:
    metadata:
      labels:
        app: api-go-depl
        tier: backend
    spec:
      containers:
      - name: api-go-depl
        image: diegodutka/go_api_ac_dd
---
apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: prod
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
spec:
  type: NodePort
  selector:
    app: api-go-depl
  ports:
    - port: 9090
      targetPort: 9090
      nodePort: 30301
  type: LoadBalancer

